### Create book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "test"
}

### Get books
GET http://localhost:8080/books

### Create books
POST http://localhost:8080/books/load
Content-Type: application/json

< ./out.json